### ISSUE TITLE
Turn off features

### ISSUE THREAD

**Issue by MAndretti** [fcannizzaro/material-tip#2]
Hi,

thanks for your nice lib :)

But i have some questions:
- how can i show a tip without an icon (all content on left side)?
- is there a way to show only one Button (e.g. dismiss only)?

Thanks for your help.

**Comment by fcannizzaro** [comment]
check [1.0.4](https://github.com/fcannizzaro/material-tip/releases/tag/1.0.4)

Now if there is no text / icon view  is not visible.
